muban.mxpro.二级.desc = '.module-info-item:eq(4)&&Text;;;.module-info-item-content:eq(1)&&Text;.module-info-item-content:eq(0)&&Text';
muban.mxpro.二级.tabs = '#y-playList&&.module-tab-item';
var rule = {
    title:'NyaFun',
    模板:'mxpro',
    host:'https://www.nyafun.net',
    // url:'/show/fyclass/page/fypage.html',
    url:'/show/fyclassfyfilter.html',
    searchUrl: '/search/wd/**/page/fypage.html',
    filterable:1,//是否启用分类筛选,
    filter_url:'{{fl.area}}{{fl.by}}{{fl.class}}{{fl.lang}}{{fl.letter}}/page/fypage{{fl.year}}',
    filter: {
        "2":[{"key":"class","name":"剧情","value":[{"n":"全部","v":""},{"n":"奇幻","v":"/class/奇幻"},{"n":"战斗","v":"/class/战斗"},{"n":"冒险","v":"/class/冒险"},{"n":"热血","v":"/class/热血"},{"n":"日常","v":"/class/日常"},{"n":"搞笑","v":"/class/搞笑"},{"n":"后宫","v":"/class/后宫"},{"n":"异世界","v":"/class/异世界"},{"n":"穿越","v":"/class/穿越"},{"n":"治愈","v":"/class/治愈"},{"n":"爱情","v":"/class/爱情"},{"n":"狗粮","v":"/class/狗粮"},{"n":"小说改","v":"/class/小说改"},{"n":"漫画改","v":"/class/漫画改"},{"n":"游戏改","v":"/class/游戏改"},{"n":"偶像","v":"/class/偶像"},{"n":"校园","v":"/class/校园"},{"n":"催泪","v":"/class/催泪"},{"n":"青春","v":"/class/青春"},{"n":"恋爱","v":"/class/恋爱"},{"n":"机战","v":"/class/机战"},{"n":"科幻","v":"/class/科幻"},{"n":"百合","v":"/class/百合"},{"n":"音乐","v":"/class/音乐"},{"n":"悬疑","v":"/class/悬疑"},{"n":"恐怖","v":"/class/恐怖"},{"n":"运动","v":"/class/运动"},{"n":"性转","v":"/class/性转"},{"n":"党争","v":"/class/党争"}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""},{"n":"日本","v":"/area/日本"},{"n":"美国","v":"/area/美国"}]},{"key":"lang","name":"语言","value":[{"n":"全部","v":""},{"n":"日语","v":"/lang/日语"},{"n":"英语","v":"/lang/英语"}]},{"key":"year","name":"年份","value":[{"n":"全部","v":""},{"n":"2023","v":"/year/2023"},{"n":"2022","v":"/year/2022"},{"n":"2021","v":"/year/2021"},{"n":"2020","v":"/year/2020"},{"n":"2019","v":"/year/2019"},{"n":"2018","v":"/year/2018"},{"n":"2017","v":"/year/2017"},{"n":"2016","v":"/year/2016"},{"n":"2015","v":"/year/2015"},{"n":"2014","v":"/year/2014"},{"n":"2013","v":"/year/2013"},{"n":"2012","v":"/year/2012"},{"n":"2011","v":"/year/2011"},{"n":"2010","v":"/year/2010"},{"n":"2009","v":"/year/2009"},{"n":"2008","v":"/year/2008"},{"n":"2007","v":"/year/2007"},{"n":"2006","v":"/year/2006"},{"n":"2005","v":"/year/2005"},{"n":"2004","v":"/year/2004"},{"n":"2003","v":"/year/2003"},{"n":"2002","v":"/year/2002"},{"n":"2001","v":"/year/2001"},{"n":"2000","v":"/year/2000"}]},{"key":"letter","name":"字母","value":[{"n":"全部","v":""},{"n":"A","v":"/letter/A"},{"n":"B","v":"/letter/B"},{"n":"C","v":"/letter/C"},{"n":"D","v":"/letter/D"},{"n":"E","v":"/letter/E"},{"n":"F","v":"/letter/F"},{"n":"G","v":"/letter/G"},{"n":"H","v":"/letter/H"},{"n":"I","v":"/letter/I"},{"n":"J","v":"/letter/J"},{"n":"K","v":"/letter/K"},{"n":"L","v":"/letter/L"},{"n":"M","v":"/letter/M"},{"n":"N","v":"/letter/N"},{"n":"O","v":"/letter/O"},{"n":"P","v":"/letter/P"},{"n":"Q","v":"/letter/Q"},{"n":"R","v":"/letter/R"},{"n":"S","v":"/letter/S"},{"n":"T","v":"/letter/T"},{"n":"U","v":"/letter/U"},{"n":"V","v":"/letter/V"},{"n":"W","v":"/letter/W"},{"n":"X","v":"/letter/X"},{"n":"Y","v":"/letter/Y"},{"n":"Z","v":"/letter/Z"},{"n":"0-9","v":"/letter/0-9"}]},{"key":"by","name":"排序","value":[{"n":"时间","v":"/by/time"},{"n":"人气","v":"/by/hits"},{"n":"评分","v":"/by/score"}]}],
        "1":[{"key":"class","name":"剧情","value":[{"n":"全部","v":""},{"n":"奇幻","v":"/class/奇幻"},{"n":"战斗","v":"/class/战斗"},{"n":"冒险","v":"/class/冒险"},{"n":"热血","v":"/class/热血"},{"n":"日常","v":"/class/日常"},{"n":"搞笑","v":"/class/搞笑"},{"n":"后宫","v":"/class/后宫"},{"n":"异世界","v":"/class/异世界"},{"n":"穿越","v":"/class/穿越"},{"n":"治愈","v":"/class/治愈"},{"n":"爱情","v":"/class/爱情"},{"n":"狗粮","v":"/class/狗粮"},{"n":"小说改","v":"/class/小说改"},{"n":"漫画改","v":"/class/漫画改"},{"n":"游戏改","v":"/class/游戏改"},{"n":"偶像","v":"/class/偶像"},{"n":"校园","v":"/class/校园"},{"n":"催泪","v":"/class/催泪"},{"n":"青春","v":"/class/青春"},{"n":"恋爱","v":"/class/恋爱"},{"n":"机战","v":"/class/机战"},{"n":"科幻","v":"/class/科幻"},{"n":"百合","v":"/class/百合"},{"n":"音乐","v":"/class/音乐"},{"n":"悬疑","v":"/class/悬疑"},{"n":"恐怖","v":"/class/恐怖"},{"n":"运动","v":"/class/运动"},{"n":"性转","v":"/class/性转"},{"n":"党争","v":"/class/党争"}]},{"key":"letter","name":"字母","value":[{"n":"全部","v":""},{"n":"A","v":"/letter/A"},{"n":"B","v":"/letter/B"},{"n":"C","v":"/letter/C"},{"n":"D","v":"/letter/D"},{"n":"E","v":"/letter/E"},{"n":"F","v":"/letter/F"},{"n":"G","v":"/letter/G"},{"n":"H","v":"/letter/H"},{"n":"I","v":"/letter/I"},{"n":"J","v":"/letter/J"},{"n":"K","v":"/letter/K"},{"n":"L","v":"/letter/L"},{"n":"M","v":"/letter/M"},{"n":"N","v":"/letter/N"},{"n":"O","v":"/letter/O"},{"n":"P","v":"/letter/P"},{"n":"Q","v":"/letter/Q"},{"n":"R","v":"/letter/R"},{"n":"S","v":"/letter/S"},{"n":"T","v":"/letter/T"},{"n":"U","v":"/letter/U"},{"n":"V","v":"/letter/V"},{"n":"W","v":"/letter/W"},{"n":"X","v":"/letter/X"},{"n":"Y","v":"/letter/Y"},{"n":"Z","v":"/letter/Z"},{"n":"0-9","v":"/letter/0-9"}]},{"key":"by","name":"排序","value":[{"n":"时间","v":"/by/time"},{"n":"人气","v":"/by/hits"},{"n":"评分","v":"/by/score"}]}],
        "107":[{"key":"letter","name":"字母","value":[{"n":"全部","v":""},{"n":"A","v":"/letter/A"},{"n":"B","v":"/letter/B"},{"n":"C","v":"/letter/C"},{"n":"D","v":"/letter/D"},{"n":"E","v":"/letter/E"},{"n":"F","v":"/letter/F"},{"n":"G","v":"/letter/G"},{"n":"H","v":"/letter/H"},{"n":"I","v":"/letter/I"},{"n":"J","v":"/letter/J"},{"n":"K","v":"/letter/K"},{"n":"L","v":"/letter/L"},{"n":"M","v":"/letter/M"},{"n":"N","v":"/letter/N"},{"n":"O","v":"/letter/O"},{"n":"P","v":"/letter/P"},{"n":"Q","v":"/letter/Q"},{"n":"R","v":"/letter/R"},{"n":"S","v":"/letter/S"},{"n":"T","v":"/letter/T"},{"n":"U","v":"/letter/U"},{"n":"V","v":"/letter/V"},{"n":"W","v":"/letter/W"},{"n":"X","v":"/letter/X"},{"n":"Y","v":"/letter/Y"},{"n":"Z","v":"/letter/Z"},{"n":"0-9","v":"/letter/0-9"}]},{"key":"by","name":"排序","value":[{"n":"时间","v":"/by/time"},{"n":"人气","v":"/by/hits"},{"n":"评分","v":"/by/score"}]}]
    },
    // class_parse: '.navbar-items&&li;a&&title;a&&href;/(\\d+).html',
    class_parse: '.navbar-items&&li:lt(5);a&&title;a&&href;/(\\w+).html',
}