var rule = {
    title:'RP影视',
    host:'https://mac.rp123.top', 
    url:'/vodshow/fyclass--hits------fypage---/',
    searchUrl:'/vodsearch/-------------/?wd=**',
    searchable:2,//是否启用全局搜索,
    quickSearch:0,//是否启用快速搜索,
    filterable:0,//是否启用分类筛选,
    headers:{'User-Agent':'MOBILE_UA',},
    class_name:'电影&电视剧&综艺&动漫&纪录片&4K专区',
    class_url:'1&2&3&4&35&40',
    推荐:'.module-poster-item;*;*;*;*',
    一级:'.module-poster-item;a&&title;.lazyload&&data-original;.module-item-note&&Text;a&&href',
    二级:{"title":"h1&&Text;.module-info-tag-link a&&Text","img":".alignnone&&src","desc":";;;.module-info-items div:eq(4) a&&Text;.module-info-items div:eq(3) a&&Text","content":".show-desc&&Text","tabs":".module-tab-items-box span","lists":".module-play-list:eq(#id) a"},
    搜索:'.module-card-item-poster;img&&alt;.lazyload&&data-original;.module-item-note&&Text;a&&href',
}