// 筛选页功能关闭中
var rule={
    title:'时光影视',
    host:'https://www.shigys.com',
    url:'/index.php/vod/type/id/fyclass/page/fypage.html',
    searchUrl:'/index.php/vod/search/page/fypage/wd/**.html',
    searchable:2,
    quickSearch:0,
    filterable:0,
    headers:{
        'User-Agent':'MOBILE_UA',
    },
    timeout:5000,
    class_name:'动作片&喜剧片&爱情片&科幻片&恐怖片&剧情片&战争片&国产剧&港台剧&日韩剧&欧美剧&综艺&动漫',
    class_url:'6&7&8&9&10&11&12&13&14&15&16&3&4',
    play_parse:true,
    lazy:'',
    limit:6,
    推荐:'.mo-cols-lays;ul.mo-cols-rows&&li;*;*;*;*',
    double:true,
    一级:'.mo-cols-lays:eq(1)&&ul.mo-cols-rows&&li;.mo-situ-name&&Text;a&&data-original;.mo-situ-rema&&Text;a&&href',
    二级:{
        "title":"h1&&Text;.mo-cols-md3--span:eq(0)&&Text",
        "img":".mo-part-full&&src",
        "desc":".mo-situ-rema:eq(0)&&Text;;;.mo-cols-md6--span:eq(1)&&Text;.mo-cols-md6--span:eq(2)&&Text",
        "content":".mo-word-info&&Text",
        "tabs":"h2.mo-fsxs-14px&&.mo-movs-btns",
        "lists":"ul.mo-movs-item:eq(#id)&&li"
    },
    搜索:'.mo-deta-info.mo-cols-rows;h1&&Text;*;*;*',
}