var rule = {
    title:'相声随身听',
    host:'https://www.xsmp3.com',
    // url:'/fyclass/fypage.html',
    url:'/fyfilter/fypage.html',
    filterable:1,//是否启用分类筛选,
    filter_url:'{{fl.cateId}}',
    filter:{
        "gdg":[{"key":"cateId","name":"分类","value":[{"n":"全部","v":"gdg"},{"n":"郭德纲单口","v":"gdg-dk"},{"n":"郭德纲于谦","v":"gdg-yq"},{"n":"郭德纲张文顺","v":"gdg-zws"},{"n":"郭德纲李菁","v":"gdg-lj"},{"n":"郭德纲徐德亮","v":"gdg-xdl"},{"n":"郭德纲何云伟","v":"gdg-hyw"},{"n":"郭德纲曹云金","v":"gdg-cyj"},{"n":"郭德纲王玥波","v":"gdg-wyb"},{"n":"郭德纲王文林","v":"gdg-wwl"}]}],
        "dys":[{"key":"cateId","name":"分类","value":[{"n":"全部","v":"dys"},{"n":"德云社精选","v":"dys-jx"},{"n":"高峰相声全集","v":"dys-gf"},{"n":"岳云鹏相声全集","v":"dys-yyp"},{"n":"郭麒麟相声全集","v":"dys-gql"},{"n":"张鹤伦相声全集","v":"dys-zhl"},{"n":"孟鹤堂相声全集","v":"dys-mht"},{"n":"徐德亮王文林","v":"xdl-wwl"},{"n":"何云伟李菁","v":"hyw-lj"},{"n":"曹云金刘云天","v":"cyj-lyt"}]}]
    },
    filter_def:{
        gdg:{cateId:'gdg'},
        dys:{cateId:'dys'},
        xsxsl:{cateId:'xsxsl'},
        qqs:{cateId:'qqs'},
        msl:{cateId:'msl'},
        hbl:{cateId:'hbl'},
        lbr:{cateId:'lbr'},
        mj:{cateId:'mj'},
        hyw:{cateId:'hyw'},
        ssj:{cateId:'ssj'},
        jk:{cateId:'jk'},
        mzm:{cateId:'mzm'},
        yzh:{cateId:'yzh'},
        swm:{cateId:'swm'}
    },
    searchUrl:'/so/**_fypage.html',
    searchable:2,
    quickSearch:0,
    headers:{
        'User-Agent':'MOBILE_UA'
    },
    timeout:5000,
    class_parse: '.list-navi&&li;a&&Text;a&&href;/(\\w+).html',
    play_parse:true,
    lazy:'js:input={jx:0,url:input,parse:0}',
    limit:6,
    推荐:'*',
    一级:'#post_list_box&&li;h2&&Text;img&&src;.f_r&&span:eq(3)&&Text;a&&href',
    二级:{
        title:'h1&&Text;.view&&Text',
        img:'img&&src',
        desc:'.view&&Text;;;.lmname&&Text;.author&&Text',
        content:'.jAsrPyf4&&p:eq(1)&&Text',
        // tabs:'js:TABS=["相声随身听"]',
        lists:'js:var VideoListJson;VideoListJson=eval(html.split("audio: ")[1].split("}\)")[0]);let list1=[];VideoListJson.forEach(function(it){list1.push(it.name.strip()+"$https:"+it.url)});LISTS=[list1];',
    },
    搜索: '*',
}