var rule = {
    title:'酷6网',
    host:'https://www.ku6.com',
    homeUrl:'/video/feed?pageNo=0&pageSize=20',
    url:'/video/feed?subjectId=fyclass&pageNo=fypage',
    class_name:'资讯&娱乐&搞笑&少儿&自制节目&影视&音乐&原创&生活&游戏&健康&汽车&时事',
    class_url:'69&70&76&73&71&72&74&75&80&93&81&47&149',
    searchUrl:'',
    searchable:0,
    quickSearch:0,
    headers:{
        'User-Agent':'MOBILE_UA',
    },
    timeout:5000,
    limit:6,
    play_parse:true,
    lazy:'js:if(/detail.html/.test(input)){var vid=input.split("~")[1];var reqUrl="https://news-stream.lsttnews.com/topic/recommend/vinfo?vid="+vid;purl=JSON.parse(request(reqUrl)).data.video.src;input={jx:0,url:purl,parse:0}}else{input={jx:0,url:input,parse:0}}',
    // lazy:'',
    推荐:'*',
    一级:'json:data;title;picPath;publisher;playUrl',
    二级:'*',
    搜索:'',
}