var rule = {
    title:'麦豆com',
    host:'https://www.mdoutv.net',
    url:'/movie_bt_series/fyclass/page/fypage',
    searchUrl:'/search/**/page/fypage',
    searchable:2,
    quickSearch:0,
    filterable:0,
    headers:{'User-Agent':'MOBILE_UA',},
    class_name:'国产&港台&欧美&韩剧&日剧&泰剧&剧集&电影&动漫&综艺',
class_url:'guocanju&gangtai&en&hanju&riju&taiju&tv&movie&ac&zongyi',
	cate_exclude:'留言|幸运码|更多播放线路|蚂蚁导航|迷历史',
    推荐:'.newindex&&ul&&li;img&&alt;img&&data-original;.jidi&&Text;a&&href',
    一级:'.mrb&&ul&&li;img&&alt;img&&data-original;.jidi&&Text;a&&href',
    二级:{"title":"h1&&Text;.moviedteail_list&&li:eq(2)&&Text;","img":".dyxingq&&img&&src","desc":".moviedteail_list&&li:eq(3)&&Text;.moviedteail_list&&li:eq(4)&&Text","content":".yp_context&&Text","tabs":".fr&&a","lists":".paly_list_btn:eq(#id) a"},
    搜索:'.search_list&&ul&&li;h3&&Text;img&&data-original;.hdinfo&&span&&Text;a&&href',
}
