{

  "站名": "素白白影视",
  "主页url": "https://www.subaibaiys.com",
  "请求头":"Referer$https://www.subaibaiys.com/",
  "分类": "电影&电视剧&热门电影&高分电影&动漫电影&香港经典电影&国产剧&欧美剧&韩剧&动漫剧",
  "分类值": "new-movie&tv-drama&hot-month&high-movie&cartoon-movie&hongkong-movie&domestic-drama&american-drama&korean-drama&anime-drama",
  "分类url": "https://www.subaibaiys.com/{cateId}/page/{catePg};;aks2",
  "数组": "<li>&&</li>",
  "副标题": "class=\"jidi\"><span>&&</span>",
  "搜索模式": "1",
  "搜索url": "https://www.subaibaiys.com/search?q={wd}",
  "影片年代": "年份：&&</li>",
  "影片地区": "地区：&&</li>",
  "影片类型": "类型：&&</li>",
  "导演": "导演：&&</li>",
  "主演": "主演：&&</li>",
  "嗅探词":".m3u8#.mp4#/m3/",
  "简介": "yp_context\">&&</p>",
  "线路数组": "mi_paly_box\">&&</div>",
  "线路标题": "ypxingq_t\">&&<span>[替换:在线播放>>素白线路]",
  "播放数组": "<div class=\"paly_list_btn\">&&</div>",
  "播放列表": "<a&&/a>",
  "播放标题": ">&&<[替换:立即播放>>空]",
  "播放链接": "href=\"&&\""
}