{
    "规则名": "独播库",
    "规则作者": "",
    "请求头参数": "手机",
    "网页编码格式": "UTF-8",
    "图片是否需要代理": "0",
    "是否开启获取首页数据": "1",  
    "首页推荐链接": "https://u.duboku.io",
    "首页列表数组规则": "body&&.myui-vodlist",
    "首页片单列表数组规则": "li",
    "首页片单是否Jsoup写法": "1",
    "分类起始页码": "1",
    "分类链接": "https://u.duboku.io/vodshow/{cateId}--{by}------{catePg}---{year}.html",
    "分类名称": "连续剧&综艺&动漫&港剧",
    "分类名称替换词": "2&3&4&20",
    "筛选数据": "ext",
    //{cateId}
    "筛选子分类名称": "陆剧&日韩剧&短剧&台泰剧&港剧||",
    "筛选子分类替换词": "13&15&21&14&20||",
    //{class}
    "筛选类型名称": "",
    "筛选类型替换词": "*",
    //{area}
    "筛选地区名称": "",
    "筛选地区替换词": "*",
    //{year}
    "筛选年份名称": "",
    "筛选年份替换词": "*",
    //{lang}
    "筛选语言名称": "",
    "筛选语言替换词": "*",
    //{by}
    "筛选排序名称": "时间&人气&评分",
    "筛选排序替换词": "time&hits&score",
    "分类截取模式": "1",
    "分类列表数组规则": ".myui-vodlist&&li",
    "分类片单是否Jsoup写法": "1",
    "分类片单标题": "h4&&a&&Text",
    "分类片单链接": "h4&&a&&href",
    "分类片单图片": ".lazyload&&data-original",
    "分类片单副标题": ".pic-text&&Text",
    "分类片单链接加前缀": "https://u.duboku.io",
    "分类片单链接加后缀": "",
    "搜索请求头参数": "User-Agent$手机",
    "搜索链接": "https://u.duboku.io/index.php/ajax/suggest?mid=1&wd={wd}",
    "POST请求数据": "",
    "搜索截取模式": "0",
    "搜索列表数组规则": "list",
    "搜索片单是否Jsoup写法": "1",
    "搜索片单图片": "pic",
    "搜索片单标题": "name",
    "搜索片单链接": "id",
    "搜索片单副标题": "",
    "搜索片单链接加前缀": "https://u.duboku.io/voddetail/",
    "搜索片单链接加后缀": ".html",
    "链接是否直接播放": "0",
    "直接播放链接加前缀": "https://live.52sf.ga/huya/",
    "直接播放链接加后缀": "#isVideo=true#",
    "直接播放直链视频请求头": "authority$ku.peizq.online#Referer$https://play.peizq.online",
    "详情是否Jsoup写法": "1",
    "类型详情": ".myui-content__detail&&p,0&&Text!分类：",
    "年代详情": "",
    "地区详情": "",
    "演员详情": ".myui-content__detail&&p,2&&Text!主演：",
    "简介详情": ".content&&Text",
    "线路列表数组规则": ".nav.nav-tabs&&li",
    "线路标题": "a&&Text",
    "播放列表数组规则": "body&&.myui-content__list",
    "选集列表数组规则": "li",
    "选集标题链接是否Jsoup写法": "1",
    "选集标题": "a&&Text",
    "选集链接": "a&&href",
    "是否反转选集序列": "0",
    "选集链接加前缀": "https://u.duboku.io",
    "选集链接加后缀": "",
    "分析MacPlayer": "2",
    "是否开启手动嗅探": "0",
    "手动嗅探视频链接关键词": ".mp4#.m3u8#.flv",
    "手动嗅探视频链接过滤词": ".html#=http"
}